# Generated by Django 2.2.9 on 2020-06-22 14:31

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('bild', stdimage.models.StdImageField(blank=True, null=True, upload_to='News/bilder/', verbose_name='Bild')),
            ],
        ),
        migrations.CreateModel(
            name='Bilder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery_app.Kategorien')),
            ],
            options={
                'ordering': ['kategorie'],
            },
        ),
    ]
