# Generated by Django 2.2.9 on 2020-06-22 14:35

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategorien',
            name='bild',
        ),
        migrations.AddField(
            model_name='bilder',
            name='bild',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='News/bilder/', verbose_name='Bild'),
        ),
        migrations.AddField(
            model_name='kategorien',
            name='title_1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='kategorien',
            name='title_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='kategorien',
            name='title_3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
