# Generated by Django 2.2.9 on 2020-06-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0002_auto_20200622_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategorien',
            name='title_1',
        ),
        migrations.RemoveField(
            model_name='kategorien',
            name='title_2',
        ),
        migrations.RemoveField(
            model_name='kategorien',
            name='title_3',
        ),
    ]
