# Generated by Django 2.2.9 on 2020-06-22 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0003_auto_20200622_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bilder',
            options={},
        ),
    ]
