# Generated by Django 2.2.9 on 2020-06-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0004_auto_20200622_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bilder',
            options={'ordering': ['kategorie']},
        ),
    ]
