# Generated by Django 2.2.9 on 2020-06-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0007_bilder_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bilder',
            options={},
        ),
        migrations.RemoveField(
            model_name='kategorien',
            name='title_2',
        ),
    ]
