# Generated by Django 2.2.9 on 2020-06-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0008_auto_20200622_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategorien',
            name='title_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
