# Generated by Django 2.2.9 on 2020-06-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0009_kategorien_title_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategorien',
            name='title_2',
        ),
    ]
