# Generated by Django 3.0.7 on 2020-06-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0010_remove_kategorien_title_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bilder',
            old_name='title',
            new_name='titel',
        ),
        migrations.RenameField(
            model_name='kategorien',
            old_name='title',
            new_name='kategorie_name',
        ),
        migrations.AddField(
            model_name='bilder',
            name='untertitel',
            field=models.TextField(blank=True, null=True, verbose_name='Untertitel'),
        ),
    ]
