# Generated by Django 3.0.7 on 2020-06-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0012_auto_20200626_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilder',
            name='datum',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Event-Datum'),
        ),
    ]
