# Generated by Django 3.0.7 on 2020-06-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0013_bilder_datum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilder',
            name='datum',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Post-Datum'),
        ),
        migrations.AlterField(
            model_name='bilder',
            name='text_1',
            field=models.TextField(blank=True, null=True, verbose_name='text_1'),
        ),
        migrations.AlterField(
            model_name='bilder',
            name='text_2',
            field=models.TextField(blank=True, null=True, verbose_name='text_2'),
        ),
    ]
