# Generated by Django 3.0.7 on 2020-07-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0016_auto_20200710_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilder',
            name='schrift_farbe',
            field=models.CharField(choices=[('SCHWARZ', 'Schwarz'), ('WEISS', 'Weiß')], default='SCHWARZ', max_length=9, verbose_name='Schriftfarbe'),
        ),
    ]
