# Generated by Django 3.0.7 on 2020-06-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255, verbose_name='Titel')),
                ('text', models.TextField(verbose_name='Text')),
                ('facebook_link', models.CharField(blank=True, max_length=300, null=True, verbose_name='Facebook Link')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Slider',
                'ordering': ['id'],
            },
        ),
    ]
