# Generated by Django 3.0.7 on 2020-06-08 10:52

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_homebeschreibung'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeslider',
            options={'ordering': ['id'], 'verbose_name': 'Start Seite Beschreibung', 'verbose_name_plural': 'Start Seite Beschreibung'},
        ),
        migrations.AddField(
            model_name='homeslider',
            name='bild',
            field=stdimage.models.StdImageField(blank=True, upload_to='News/bilder/', verbose_name='Bild'),
        ),
    ]
