# Generated by Django 3.0.7 on 2020-06-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_auto_20200608_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeslider',
            name='facebook_link',
        ),
        migrations.AddField(
            model_name='homebeschreibung',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Facebook Link'),
        ),
    ]
