# Generated by Django 3.0.7 on 2020-06-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_auto_20200608_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebeschreibung',
            name='titel_2',
        ),
        migrations.RemoveField(
            model_name='homeslider',
            name='bild',
        ),
        migrations.AddField(
            model_name='homebeschreibung',
            name='untertitel',
            field=models.TextField(blank=True, null=True, verbose_name='Untertitel'),
        ),
    ]
