# Generated by Django 3.0.7 on 2020-06-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KontaktBeschreibungen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Beschreibung',
                'verbose_name_plural': 'Beschreibungen',
            },
        ),
        migrations.CreateModel(
            name='KontaktInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Treeathlon - Bewegen, Begrünen, Begeistern', max_length=300, verbose_name='Treeathlon Name')),
                ('adresse', models.CharField(max_length=300, verbose_name='Adresse')),
                ('telefon', models.CharField(blank=True, max_length=300, null=True, verbose_name='Treeathlon Telefon Nr.')),
                ('email', models.CharField(max_length=300, verbose_name='Treeathlon E-Mail Adresse')),
                ('facebook_link', models.CharField(blank=True, max_length=300, null=True, verbose_name='Facebook Link')),
                ('instagram_link', models.CharField(blank=True, max_length=300, null=True, verbose_name='Instagram Link')),
                ('twitter_link', models.CharField(blank=True, max_length=300, null=True, verbose_name='Twitter Link')),
                ('iban', models.CharField(max_length=300, verbose_name='Treeathlon IBAN')),
                ('zvr_zahl', models.CharField(max_length=300, verbose_name='ZVR-Zahl')),
            ],
            options={
                'verbose_name': 'Kontaktinfo',
                'verbose_name_plural': ' Kontaktinfos',
                'ordering': ['id'],
            },
        ),
    ]
