# Generated by Django 3.0.7 on 2020-06-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0003_auto_20200608_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontaktinfo',
            name='facebook_link',
        ),
    ]
