# Generated by Django 3.0.7 on 2020-06-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0005_kontaktinfo_facebook_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KontaktBeschreibungen',
        ),
        migrations.AddField(
            model_name='kontaktinfo',
            name='beschreibung',
            field=models.TextField(blank=True, null=True),
        ),
    ]
