# Generated by Django 3.0.7 on 2020-06-05 11:05

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=300, verbose_name='Überschrift')),
                ('text_1', models.TextField(blank=True, null=True, verbose_name='Text 1')),
                ('bild', stdimage.models.StdImageField(blank=True, upload_to='News/bilder/', verbose_name='Bild')),
                ('pdf', models.FileField(blank=True, upload_to='News/pdf/')),
                ('datum', models.DateTimeField(blank=True, null=True, verbose_name='Event-Datum')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
