# Generated by Django 3.0.7 on 2020-06-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='text_2',
            field=models.TextField(default='text 2', verbose_name='Text 2'),
        ),
    ]
