# Generated by Django 3.0.7 on 2020-06-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_auto_20200605_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
