# Generated by Django 3.0.7 on 2020-07-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_auto_20200605_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsmodel',
            options={'ordering': ['reihenfolge'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='reihenfolge',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
