# Generated by Django 3.0.7 on 2020-07-13 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_auto_20200713_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsmodel',
            options={'ordering': ['erstellt_am'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='reihenfolge',
        ),
    ]
