# Generated by Django 3.0.7 on 2020-07-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0008_auto_20200713_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsmodel',
            options={'ordering': ['-erstellt_am'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='farbe',
            field=models.CharField(choices=[('schwarz', 'schwarz'), ('weiss', 'weiss')], default='weiss', max_length=9),
        ),
    ]
