# Generated by Django 3.0.7 on 2020-07-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0009_auto_20200713_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='farbe',
            field=models.CharField(choices=[('Schwarz', 'Schwarz'), ('Weiß', 'Weiß')], default='weiss', max_length=9),
        ),
    ]
