# Generated by Django 3.0.7 on 2020-07-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0010_auto_20200713_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='farbe',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='schrift_farbe',
            field=models.CharField(choices=[('Schwarz', 'Schwarz'), ('Weiß', 'Weiß')], default='weiss', max_length=9),
        ),
    ]
