# Generated by Django 3.0.7 on 2020-07-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0011_auto_20200713_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='schrift_farbe',
            field=models.CharField(choices=[('Schwarz', 'Schwarz'), ('Weiß', 'Weiß')], max_length=9, verbose_name='Schrift Farbe'),
        ),
    ]
