# Generated by Django 3.0.7 on 2020-06-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('aufgaben', models.CharField(blank=True, max_length=300, verbose_name='Aufgaben')),
                ('beschreibung', models.TextField(default='text', verbose_name='Obere Beschreibung')),
            ],
            options={
                'verbose_name': 'Beschreibung über mich',
                'verbose_name_plural': ' Beschreibungen über mich',
            },
        ),
        migrations.CreateModel(
            name='UeberUnsBeschreibungen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=300, verbose_name='Überschrift')),
                ('beschreibung', models.TextField(blank=True, null=True, verbose_name='Untere Beschreibung')),
            ],
            options={
                'verbose_name': 'Beschreibung',
                'verbose_name_plural': 'Beschreibungen',
            },
        ),
    ]
