# Generated by Django 3.0.7 on 2020-06-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UeberUnsBeschreibungen',
            new_name='UeberMichBeschreibungen',
        ),
        migrations.AlterModelOptions(
            name='aboutmodel',
            options={'verbose_name': 'Hauptbeschreibung', 'verbose_name_plural': ' Die Hauptbeschreibungen'},
        ),
        migrations.AlterModelOptions(
            name='uebermichbeschreibungen',
            options={'verbose_name': 'Zusetzliche Beschreibung', 'verbose_name_plural': 'Zusetzliche Beschreibungen'},
        ),
    ]
