# Generated by Django 3.0.7 on 2020-06-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0002_auto_20200608_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutmodel',
            options={'verbose_name': ' erste Beschreibung', 'verbose_name_plural': ' Die erste Beschreibung'},
        ),
        migrations.AlterModelOptions(
            name='uebermichbeschreibungen',
            options={'verbose_name': 'zweite Beschreibung', 'verbose_name_plural': 'Die zweite Beschreibung'},
        ),
    ]
